# Generated by Django 4.0.3 on 2022-05-29 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='hora_entrega',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.CharField(choices=[('IN', 'Indefinido'), ('D', 'Design'), ('EV', 'Edição de Vídeo')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='prazo_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='referencias',
            field=models.ManyToManyField(blank=True, to='jobs.referencias'),
        ),
    ]
