# Generated by Django 4.0.3 on 2022-07-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobs_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='referencias',
            field=models.ManyToManyField(blank=True, help_text='Imagens de referência de qualidade para o trabalho', to='jobs.referencias'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='reservado',
            field=models.BooleanField(default=False, help_text='Define se o trabalho está reservado para um profissional específico. Atualizado automaticamente.'),
        ),
    ]
