# Generated by Django 4.0.3 on 2022-07-03 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobs_categoria_alter_jobs_referencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='arquivo_final',
            field=models.FileField(blank=True, help_text='Arquivo anexado para entrega pelo profissional', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory'),
        ),
    ]
