# Generated by Django 4.0.3 on 2022-07-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_arquivo_final_alter_jobs_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='referencias',
            options={'verbose_name': 'Imagem de Referência', 'verbose_name_plural': 'Imagens de Referência'},
        ),
        migrations.AddField(
            model_name='referencias',
            name='titulo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
